version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fcjdmsapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eu65yptq2x69"
s3_prefix = "fcjdmsapp"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DocumentStoreBucketName=\"fcjdmsstore-2025\" WebStoreBucketName=\"fcjdmswebstore-2025\" MasterUserName=\"admin\" MasterPassword=\"Admin1234@\" DomainName=\"my-es-domain\""
image_repositories = []
